This is for AI Session # 35 recording
https://www.h2ktrainingvideos.com/ai_new-recorded_session-36/ 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

Linear Regression is a supervised ML algirithm used to predict the continus values By finding the linear relationshop between X(input) and Y(Output)

It will try to draw a straght line that best fits my data.

mathematical representaion y=mx+b y-predicted output x-input feature m-slope b-intercept

hours(x) marks(y) 1 40 2 50 3 60 4 70 5 80

marks=m*hours +b

After training we get-->marks=8*hours+30

if a student stidues 5 hours

marks=8*5+30=70

Goal of linear regression--->find the best fitting line

Here the meaning of best is simlpy "the line minimizes the error".

-->Here we need to measure the Error(Cost function) using

Mean Squared Error-->1/n summation of (actual-predicted)square

How model learns?

Here we are using sklearn library sklearn.linear_model --->JHere it uses ordinary least square (OLS)

(X transpose * X )power -1 * (x transpose *y)

In [ ]:
#x and y-->Simple linear regression
# x1,x2,x3,x4....-->Multi linear regression
##sqfeet,no of rooms --->X-->y=w1x1+w2x2+b
#price--?y

In [2]:
x=np.array([[1400,2],[2000,3],[3200,3]])
y=np.array([400,800,1200])#output

In [3]:
x.shape

(3, 2)

In [4]:
x

array([[1400,    2],
       [2000,    3],
       [3200,    3]])

In [5]:
y

array([ 400,  800, 1200])

Mathematically representation of y=mx+c y=2x+1 here m=2

if x increases by 1 ,y increases by 2

c-->intercept

the value of y when x=0

y=2x+1

if x=0

y=2(0)+1 y=1

In machine learning:
we write the same equatoin as y=wx+b

w-->weight(m) b=bias(c)

In [6]:
model=LinearRegression()#y=w1x1+w2x2+b
model.fit(x,y)

#so here how much of y changes when x changes
#IT is the rate of change between x and y

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [7]:
model

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [8]:
model.coef_

array([  0.33333333, 200.        ])

In [9]:
w1=model.coef_[0]
w2=model.coef_[1]

In [10]:
b=model.intercept_

In [11]:
w1

np.float64(0.33333333333333337)

In [12]:
w2

np.float64(199.9999999999999)

In [13]:
b

np.float64(-466.6666666666663)

In [14]:
x_new=[[1400,2]]
y_pred=model.predict(x_new)
#y=b+w1x1+w2x2

In [15]:
y_pred

array([400.])

In [16]:
x

array([[1400,    2],
       [2000,    3],
       [3200,    3]])

In [17]:
y

array([ 400,  800, 1200])

In [18]:
model.predict(x)

array([ 400.,  800., 1200.])

In [19]:
#Linear regression with Gradient Descent
import numpy as np
x=np.array([[2,4],[4,7],[6,8],[8,9],[10,10]])

In [20]:
x.shape

(5, 2)

In [21]:
x

array([[ 2,  4],
       [ 4,  7],
       [ 6,  8],
       [ 8,  9],
       [10, 10]])

In [22]:
x.T

array([[ 2,  4,  6,  8, 10],
       [ 4,  7,  8,  9, 10]])

In [23]:
samples,features=x.shape

In [24]:
samples

5

In [25]:
features

2

In [26]:
y=np.array([50,60,70,80,96])

In [27]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
w=np.zeros(features)#[w1,w2]
b=0

In [29]:
w

array([0., 0.])

In [30]:
b

0

In [31]:
epochs=100#going through the dataset fully one time here we taken 100 that means 100 times going thourgh the dataset
learning_rate=0.01

In [32]:
y_pred=np.dot(x,w)+b#y=b+w1x1+w2x2

In [33]:
y_pred

array([0., 0., 0., 0., 0.])

In [34]:
y

array([50, 60, 70, 80, 96])

In [35]:
error=y-y_pred

In [36]:
error.shape

(5,)

In [37]:
error

array([50., 60., 70., 80., 96.])

MAtrix multiplication rule

(3,4)(4,3) (2 5)(5,)

()

In [38]:
y

array([50, 60, 70, 80, 96])

In [45]:
# This is without learning rate
for epoch in range(epochs):

    #Prediction
    y_pred=np.dot(x,w)+b#y=b+w1x1+w2x2

    error=y_pred-y

    #gradients
    dw=(1/samples)*np.dot(x.T,error)
    #if i slighlty change the w then how much loss change?
    #differentiaon(derivative) of weight wrt loss--
    #dl/dw=1/n(X.T)(y_predicted-y_actual)
    
    db=(1/samples)*np.sum(error)
    #derivative of loss wr.to bias
    #dl/db=1/n * total sum

    #update my parameters
    #learning rate is a parameter that controls how much the model updates itw weight dduring each step of training

    w=w-(dw)############without learning rate#############
    b=b-(db)

    print("epoch",epoch)
    print("weights and bias ",w,b)
    print("y_pred",y_pred)
    print()

epoch 0
weights and bias  [0.10751016 8.63601952] 4.133339266642496
y_pred [36.08085147 61.95975254 72.73859293 83.51743332 94.29627371]

epoch 1
weights and bias  [0.41282807 8.28491063] 4.921190682932377
y_pred [38.89243767 65.01551656 73.86655639 82.71759623 91.56863607]

epoch 2
weights and bias  [0.53382461 8.08260517] 5.757710788844657
y_pred [38.88648934 64.56687738 73.67744415 82.78801092 91.89857769]

epoch 3
weights and bias  [0.66989211 7.87066234] 6.5692530169401255
y_pred [39.1557807  64.47124544 73.62149984 82.77175424 91.92200864]

epoch 4
weights and bias  [0.8012094  7.66479835] 7.363613562931635
y_pred [39.39168659 64.34345783 73.55390439 82.76435095 91.97479751]

epoch 5
weights and bias  [0.92863859 7.46191591] 8.140276094759022
y_pred [39.62522578 64.22203965 73.48925681 82.75647397 92.02369113]

epoch 6
weights and bias  [1.17678946 7.41073535] 8.91760754082525
y_pred [39.84521692 64.08824183 73.40743492 82.726628   92.04582109]

epoch 7
weights and bias  [-11.537

In [47]:
w=np.zeros(features)#[w1,w2]
b=0

In [48]:
w

array([0., 0.])

In [49]:
b

0

In [50]:
# This iw with a learning rare
for epoch in range(epochs):

    #Prediction
    y_pred=np.dot(x,w)+b#y=b+w1x1+w2x2

    error=y_pred-y

    #gradients
    dw=(1/samples)*np.dot(x.T,error)
    #if i slighlty change the w then how much loss change?
    #differentiaon(derivative) of weight wrt loss--
    #dl/dw=1/n(X.T)(y_predicted-y_actual)
    
    db=(1/samples)*np.sum(error)
    #derivative of loss wr.to bias
    #dl/db=1/n * total sum

    #update my parameters
    #learning rate is a parameter that controls how much the model updates itw weight dduring each step of training

    w=w-(learning_rate*dw)############### with learning rate #############
    b=b-(learning_rate*db)

    print("epoch",epoch)
    print("weights and bias ",w,b)
    print("y_pred",y_pred)
    print()

epoch 0
weights and bias  [4.72 5.72] 0.7120000000000001
y_pred [0. 0. 0. 0. 0.]

epoch 1
weights and bias  [4.39184  5.422848] 0.69896
y_pred [ 33.032  59.632  74.792  89.952 105.112]

epoch 2
weights and bias  [4.36099462 5.4789392 ] 0.728323552
y_pred [31.174032 56.226256 70.432784 84.639312 98.84584 ]

epoch 3
weights and bias  [4.31324071 5.51381506] 0.75498125984
y_pred [31.3660696  56.52487645 70.7258049  84.92673334 99.12766179]

epoch 4
weights and bias  [4.26704261 5.54949191] 0.78158706043584
y_pred [31.43672291 56.60464949 70.74494596 84.88524243 99.0255389 ]

epoch 5
weights and bias  [4.22130878 5.58468049] 0.8079872484613388
y_pred [31.5136399  56.69620083 70.77977796 84.86335508 98.94693221]

epoch 6
weights and bias  [4.17609727 5.61946146] 0.8341931317036579
y_pred [31.58932678 56.78598582 70.81328387 84.84058193 98.86787998]

epoch 7
weights and bias  [4.13139862 5.65383487] 0.8602062931841818
y_pred [31.66423351 56.87481243 70.84646844 84.81812444 98.78978044]

epoc

In [51]:
y

array([50, 60, 70, 80, 96])

In [41]:
w

array([1.61440502, 7.55003034])

In [42]:
b

np.float64(2.6519200614622673)

In [43]:
x_new=np.array([5,9])
y_new=np.dot(x_new,w)+b

In [44]:
y_new

np.float64(78.6742182492257)

End of code