# numpy: 26.0.1 Installed 03/11/2026

pip install numpy
C:\Users\jaiam>pip install numpy
Requirement already satisfied: numpy in c:\users\jaiam\appdata\local\programs\python\python311\lib\site-packages (2.3.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Numerical python it is one of the most library in python for computing and AI/ML.
It is a foundation library for other like - Tensorflow, pytorch, pandas, scikitlearn

-->Numerical computations
--> It will handle large arrays
--> Matrics kind of computaions we can do.
--> Linear algebra
--> Statistics

Numerical Python--->numerical computations on top of arrays

It is very fast and efficent to do operations on large datasets

Backbone of all ML libraries--pandas,matplotlib,seaborn,tensorflow,pytorch...

# ### # AI?
$$
Here we depedent upon heavy mathematical operations so here numpy will perform this things

Ex:
Image processing

Nueral network

Time series kind of data

Deep learning

Install numpy
pip install numpy

Array:
DAta strucutre used to store multiple values of the same type.

all the elements must be in the same type

each element we can access by index--starts with 0

One dimenisanla arrays

Two

three ...

n dimenionsnal

pip install numpy

In [200]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [201]:
type(a)

numpy.ndarray

In [202]:
# Let's take a list
a=[3,4,5,6]
b=[4,5,6,7]

a+b

[3, 4, 5, 6, 4, 5, 6, 7]

In [203]:
# Try to add two elemets using for loop
r=[]
for i in a:
    for i in b:
        i=a+b
        print(i)

[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]
[3, 4, 5, 6, 4, 5, 6, 7]


In [204]:
a=[3,4,5,6]
b=[4,5,6,7]
a

[3, 4, 5, 6]

In [205]:
b

[4, 5, 6, 7]

In [206]:
r=[]
for i in range(len(a)):
   r.append(a[i]+b[i])


r

[7, 9, 11, 13]

In [207]:
# Using numpy we can do this 
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [208]:
a*b #Element wise multiplication

array([ 4, 10, 18, 28])

Main objective of numpy is array
It represent the data in diff dimensions
N - Dimensional array
1d,2D,3D,4D.........N dimension

Array:
------
Collection of elememts (numbers) stored in a single veriable in an orderd structure
[10,20,30,40]--> student marks
[4.5, 3.4, 2.3, 6.7]
Types of array:
---------------

1D array--Vector
[30,40,50,60]

2D array: Matrix--Colums and rows
----------------------------------

[[2,3],[4,5]]--> city and state, student id

3D array:
---------


In [209]:
import numpy as np
a=np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [210]:
a.shape

(4,)

In [211]:
a.ndim

1

In [212]:
a.size

4

In [213]:
b=np.array([[2,3,4],[5,6,7]])# rows and columns --Matrix
b

array([[2, 3, 4],
       [5, 6, 7]])

In [214]:
b.shape

(2, 3)

In [215]:
b.ndim

2

In [216]:
b.size

6

In [217]:
c=np.array([[[3,4,5],[6,7,8]]])
c

array([[[3, 4, 5],
        [6, 7, 8]]])

In [218]:
c.shape

(1, 2, 3)

In [219]:
c.ndim

3

In [220]:
c.size

6

In [221]:
c=np.array([[[3,4,5],[6,7,8],[3,4,5],[6,7,8]]])
c

array([[[3, 4, 5],
        [6, 7, 8],
        [3, 4, 5],
        [6, 7, 8]]])

In [222]:
c.shape

(1, 4, 3)

In [223]:
c.ndim

3

In [224]:
# If one is float than it will convert all to float
c=np.array([[[3,4,5],[6,7,8],[3.2,2.2,4],[6,7,8]]])
c

array([[[3. , 4. , 5. ],
        [6. , 7. , 8. ],
        [3.2, 2.2, 4. ],
        [6. , 7. , 8. ]]])

AI Session # 19 Numpay cont

In [225]:
c=np.array([[[4,5,6],[7,8,9],[3,2,1]],[[4,5,6],[7,8,9],[3,2,1]]])
c           

array([[[4, 5, 6],
        [7, 8, 9],
        [3, 2, 1]],

       [[4, 5, 6],
        [7, 8, 9],
        [3, 2, 1]]])

In [226]:
c.ndim

3

In [227]:
c.shape

(2, 3, 3)

In [228]:
c.size

18

In [229]:
#real time examples how we can represent the in one dimen, two, 3d....
# ONE dim
emp_Salary=np.array([30000,40000])

In [230]:
#2 dime
student_data=np.array([[55,60,70],[56,67,98],[98,65,33]])
student_data

array([[55, 60, 70],
       [56, 67, 98],
       [98, 65, 33]])

#Sales data

#3 dimen

#3 stores
#4 weeks of sales
#3 products

#stores * weeks * products -->3D
sales_data=np.array([[[40,50,60],[50,60,70],[80,90,100],[80,90,100]],[[10,20,30],[60,80,70],[80,90,100],[90,20,300]],[[80,20,30],[80,90,100],[90,80,70],[90,20,300]]])

In [231]:
sales_data=np.array([[[40,50,60],[50,60,70],[80,90,100],[80,90,100]],[[10,20,30],[60,80,70],[80,90,100],[90,20,300]],[[80,20,30],[80,90,100],[90,80,70],[90,20,300]]])

In [232]:
sales_data

array([[[ 40,  50,  60],
        [ 50,  60,  70],
        [ 80,  90, 100],
        [ 80,  90, 100]],

       [[ 10,  20,  30],
        [ 60,  80,  70],
        [ 80,  90, 100],
        [ 90,  20, 300]],

       [[ 80,  20,  30],
        [ 80,  90, 100],
        [ 90,  80,  70],
        [ 90,  20, 300]]])

In [233]:
sales_data.shape

(3, 4, 3)

Image
Width

height

3 color channels-->RED,Green , blue

2,2,3

the values take as pixel values--0 to 255

In [234]:
image=np.array([[[255,0,0],[0,0,255]],[[120,120,0],[0,0,255]]])#2,2,3

In [235]:
#i want 3,3,3
image2=np.array([[[255,0,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]]])

In [236]:
image

array([[[255,   0,   0],
        [  0,   0, 255]],

       [[120, 120,   0],
        [  0,   0, 255]]])

In [237]:
image.shape

(2, 2, 3)

In [238]:
image=np.array([[[255,0,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]]])

In [239]:
image.shape

(3, 3, 3)

In [240]:
image

array([[[255,   0,   0],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[120, 120,   0],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[120, 120,   0],
        [  0,   0, 255],
        [  0,   0, 255]]])

Mathmatical operations

In [241]:
a

array([2, 3, 4, 5])

In [242]:
a+2

array([4, 5, 6, 7])

In [243]:
a*2

array([ 4,  6,  8, 10])

In [244]:
b=np.array([[1,2,3],[4,5,6]])

In [245]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
b*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [247]:
b/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [248]:
c=np.array([[[4, 5, 6],
        [7, 8, 9],
        [3, 2, 1]],

       [[1, 5, 6],
        [4, 8, 9],
        [5, 2, 1]]])
c

array([[[4, 5, 6],
        [7, 8, 9],
        [3, 2, 1]],

       [[1, 5, 6],
        [4, 8, 9],
        [5, 2, 1]]])

In [249]:
c*6

array([[[24, 30, 36],
        [42, 48, 54],
        [18, 12,  6]],

       [[ 6, 30, 36],
        [24, 48, 54],
        [30, 12,  6]]])

In [250]:
a.sum()

np.int64(14)

In [251]:
a.mean()

np.float64(3.5)

In [252]:
b.max()

np.int64(6)

Special functions

In [253]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [254]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [255]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [256]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [257]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [258]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [259]:
np.linspace(10,20,3)#start,stop,num->total no of values to generate evenly spaced numbers between 10 and 20

array([10., 15., 20.])

In [260]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [261]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [262]:
np.linspace(10,20,3)#start,stop,num->total no of values to generate evenly spaced numbers between 10 and 20

array([10., 15., 20.])

In [263]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [264]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [265]:
np.linspace(10,20,1)#start, stop,num ->total no of values to generate evenly spaced numbers between 10 and 20

array([10.])

In [266]:
np.linspace(10,20,2)

array([10., 20.])

In [267]:
np.linspace(10,20,3)

array([10., 15., 20.])

To be done from here @26.59 STOP AI Session #19

Matrix operations

In [268]:
A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[5,6],[7,8]])

In [269]:
A

array([[1, 2],
       [3, 4]])

In [270]:
B

array([[4, 5],
       [5, 6],
       [7, 8]])

In [271]:
B1=np.array([[4,2],[9,2]])
B1

array([[4, 2],
       [9, 2]])

In [272]:
A*B1#both are 2*2 matrix

array([[ 4,  4],
       [27,  8]])

In [273]:
A*B#For doing a normal multiplication the each matrix will be same size

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

Dimension matching

No of columns in the first matrix = no of rows in the second

A:23 B-34

In [ ]:
#i wana do matrix multiplication
#For matrix multiplication the rule is the no of columns of first matrix will be match with no of rows of sencond matrix
#first matrix-->m*n
#second amtrix -->n*p
C=np.dot(A,B)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
B

array([[4, 5],
       [5, 6],
       [7, 8]])

In [ ]:
B.shape

(3, 2)

In [ ]:
A.shape

(2, 2)

In [ ]:
np.dot(B,A)

array([[19, 28],
       [23, 34],
       [31, 46]])

In [ ]:
B

array([[4, 5],
       [5, 6],
       [7, 8]])

In [ ]:
#transpose

B.T#rows becomes columns

array([[4, 5, 7],
       [5, 6, 8]])

Indexing

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a[0]

np.int64(1)

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0][1]

np.int64(2)

In [ ]:
b[1]

array([4, 5, 6])

In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
b[1][2]

np.int64(6)

In [ ]:
c=np.array([[4,5,6],[7,8,9],[3,2,1]])
c

array([[4, 5, 6],
       [7, 8, 9],
       [3, 2, 1]])

In [ ]:
c[0][1][2]

np.int64(9)

In [ ]:

c[0][1][2]

np.int64(9)

In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
b[0][1]

np.int64(2)

In [ ]:
b[0,1]

np.int64(2)

In [ ]:
c=np.array([[[4, 5, 6],[7, 8, 9],[3, 2, 1]],[[1, 5, 6],[4, 8, 9],[5, 2, 1]]])
c

array([[[4, 5, 6],
        [7, 8, 9],
        [3, 2, 1]],

       [[1, 5, 6],
        [4, 8, 9],
        [5, 2, 1]]])

In [ ]:
c[0]

array([[4, 5, 6],
       [7, 8, 9],
       [3, 2, 1]])

In [ ]:
c[0][1]

array([7, 8, 9])

In [ ]:
c[1][1][2]

np.int64(9)

In [ ]:
c[1]

array([[1, 5, 6],
       [4, 8, 9],
       [5, 2, 1]])

AI Session # 20 start from here

Random number generations AI Session #20 Recording

In [ ]:
import numpy as np

In [ ]:
np.random.randint(10,100,10)#will generate 10 number

array([44, 62, 42, 37, 74, 88, 68, 42, 27, 23], dtype=int32)

# If we do not use np than will not accept 3rd parameter
random.randint(10,20,100)

In [ ]:
np.random.randint(10,20)

11

In [ ]:
np.random.randint(10,100)#will generate one number because we did not gave 3rd parameter here

33

In [ ]:
np.random.randint(10,100,5)# If we add one more parameter 5 than it will generate 5 int numbers

array([86, 62, 55, 24, 68], dtype=int32)

In [ ]:
np.random.random()#Will generate float value between 0 to 1

0.16001007403150314

In [ ]:
np.random.random()

0.9306713333386005

In [ ]:
import random
random.randint(10,20)

20

In [ ]:
import random#Without using np
random.randint(10,20)
random.random()

0.6423511195151169

In [ ]:
np.random.uniform(10,100,10)

array([97.43689244, 51.83753744, 97.27839741, 27.69282306, 91.41745844,
       11.24399837, 59.07728821, 48.07471549, 57.25790609, 59.81003488])

In [ ]:
np.random.uniform(10,200,10)#Every number in a given range has equql probability being selected.

array([ 83.91595727, 199.65759091, 195.53636616, 192.73162157,
       196.026159  , 160.67235577, 197.83219102, 179.5484428 ,
        89.02720104, 159.10765059])

In [ ]:
np.random.uniform(10,200,20)

array([193.97196743,  98.58524559,  60.17732227, 114.38189939,
        81.69341958,  48.70838612, 183.93787481, 188.44371035,
       169.12378259,  92.22997369, 146.06146087, 171.75535823,
        25.01887021,  87.89212187, 131.89831915, 195.52575122,
       144.00478826, 130.95781952,  49.02347506,  65.68237146])

In [ ]:
np.random.seed(99)#Fixed value will generate
np.random.randint(10,100,10)

array([11, 45, 67, 50, 83, 92, 78, 79, 62, 11], dtype=int32)

In [ ]:
np.random.seed(42)#Freezing value using seed
np.random.randint(10,100,10)

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97], dtype=int32)

image=np.array([[[255,0,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]]])
Take this and create using random modual.

In [ ]:
image=np.array([[[255,0,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]],[[120,120,0],[0,0,255],[0,0,255]]])
image

array([[[255,   0,   0],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[120, 120,   0],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[120, 120,   0],
        [  0,   0, 255],
        [  0,   0, 255]]])

In [ ]:
#I want the shape of 100*100^3
np.random.randint(0,100,3)

array([ 1, 87, 29], dtype=int32)

In [ ]:
r=np.random.randint(0,100,3)
r.shape

(3,)

In [ ]:
#I want the shape of 100*100^3
np.random.randint(0,255,10)

array([187,  20, 160, 203,  57,  21, 252, 235,  88,  48], dtype=int32)

In [ ]:
#I want the shape of 100*100^3
r=np.random.randint(0,255,10*2)
r

array([218,  58, 254, 169, 219, 187, 207,  14, 189, 189, 174, 189,  50,
       107,  54, 243,  63, 248, 130, 228], dtype=int32)

In [ ]:
#I want the shape of 100*100^3
r=np.random.randint(0,255,(10,2))
r

array([[ 32, 206],
       [ 14,  13],
       [166,  62],
       [  4, 243],
       [120,  89],
       [239, 208],
       [106, 238],
       [179,  15],
       [ 98, 165],
       [ 52, 214]], dtype=int32)

In [ ]:
#I want the shape of 100*100^3
r=np.random.randint(0,255,(100,100,3))
r

array([[[186, 163, 146],
        [ 89, 194, 254],
        [146, 147,  95],
        ...,
        [ 57, 121,   0],
        [238,  33,  95],
        [125, 117,  47]],

       [[ 88, 231, 236],
        [116, 128,  15],
        [188, 230, 191],
        ...,
        [ 55, 160, 165],
        [116, 133,  57],
        [ 43, 172, 159]],

       [[172,  60,  46],
        [148,  79, 117],
        [212, 202, 251],
        ...,
        [ 35,   0,   7],
        [112,  98, 252],
        [179, 206,  46]],

       ...,

       [[ 51, 102, 100],
        [141, 200, 201],
        [ 62, 198,  27],
        ...,
        [ 96,  52, 144],
        [ 63, 211,  60],
        [184, 204, 107]],

       [[215, 245, 238],
        [247,  36, 134],
        [  7, 214,  77],
        ...,
        [172,  32, 201],
        [ 72, 176, 160],
        [224, 198, 195]],

       [[ 27,  86,  52],
        [223,  43,  79],
        [237, 182, 137],
        ...,
        [ 35,   9,  25],
        [ 19, 124,  43],
        [ 61, 200,  78]]

In [ ]:
r.shape

(100, 100, 3)